# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='HiredEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='data_migration.department')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='data_migration.job')),
            ],
            options={
                'verbose_name': 'Hired Employee',
                'verbose_name_plural': 'Hired Employees',
                'db_table': 'hired_employees',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Migration Log',
                'verbose_name_plural': 'Migration Logs',
                'db_table': 'data_migration_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
